Employee/Employee.Web/Models/ErrorViewModel.cs
using System;

namespace Employee.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Employee/Employee.Web/Areas/User/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Employee.Web.Controllers
{
    [Area("User")]
    public class EmployeeController : Controller
    {
        private readonly IEmployeeService _employeeService;
        private ReturnModel _returnModel;
        public EmployeeController(IEmployeeService employeeService)
        
        {
            this._employeeService = employeeService;
            this._returnModel = new ReturnModel();
            _returnModel.Message = Constants.SERVER_ERROR_OCCURRED;
        }
        public async Task<ActionResult> Index()
        {
          

            List<EmployeeDetailsEntity> model = new List<EmployeeDetailsEntity>();
            _returnModel = await _employeeService.GetEmployeeList();
      
   
            if (_returnModel.IsSuccess)
            {
                ViewBag.EmployeeList = _returnModel.Data;
                return View("~/Areas/User/Views/EmpForm/Index.cshtml");
            }

            else
            {
                ViewBag.EmpList = model;
                TempData["Msg"] = _returnModel.Message;
                return View("~/Areas/User/Views/EmpForm/Index.cshtml");
            }
        }

        [HttpGet]
        public ActionResult AddEmployee()
        {
            return View("~/Areas/User/Views/EmpForm/Index.cshtml", new EmployeeDetailsEntity());
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> AddEmployee(EmployeeViewModel model)
        {
            if (!ModelState.IsValid)
            {
                _returnModel.Message = ModelState.FirstOrDefault(x => x.Value.Errors.Any()).Value.Errors.FirstOrDefault().ErrorMessage;
                return Json(_returnModel);
            }

            _returnModel = await _employeeService.CreateEmployee(model);
            return Json(_returnModel);
        }


        [HttpGet]
        public async Task<ActionResult> EditEmployee(int EmployeeId)
        {
            ParentModel parent = new ParentModel();
            EmployeeDetailsEntity model = new EmployeeDetailsEntity();
            _returnModel = await _employeeService.GetEmployeeById(EmployeeId);

            List<EmployeeDetailsEntity> res = new List<EmployeeDetailsEntity>();
            ViewBag.EmployeeList = res;

            if (_returnModel.IsSuccess)
            {            
                return View("~/Areas/User/Views/EmpForm/Index.cshtml", _returnModel.Data);
            }
            else
            {
                TempData["Msg"] = _returnModel.Message;
                return View("~/Areas/User/Views/EmpForm/Index.cshtml", model);
            }
        }


        [HttpPost]
        public async Task<JsonResult> EditEmployee(EmployeeUpdateViewModel model)
        {

            if (!ModelState.IsValid)
            {
                _returnModel.Message = ModelState.FirstOrDefault(x => x.Value.Errors.Any()).Value.Errors.FirstOrDefault().ErrorMessage;
                return Json(_returnModel);
            }

            _returnModel = await _employeeService.UpdateEmployee(model);
            return Json(_returnModel);
        }


        public async Task<JsonResult> DeleteEmployee(int EmployeeId)
        {
            _returnModel = await _employeeService.DeleteEmployee(EmployeeId);
            return Json(_returnModel);
        }


        public async Task<JsonResult> ActivateEmployee(int EmployeeId)
        {
            _returnModel = await _employeeService.ActivateEmployee(EmployeeId);
            return Json(_returnModel);
        }


        public async Task<JsonResult> DeActivateEmployee(int EmployeeId)
        {
            _returnModel = await _employeeService.DeActivateEmployee(EmployeeId);
            return Json(_returnModel);
        }
    }
}

Employee/Employee.Web/Areas/User/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Employee.Web.Controllers
{
    [Area("User")]
    public class LoginController : Controller
    {
        private readonly IEmployeeService _employeeService;
        private ReturnModel _returnModel;
        public LoginController(IEmployeeService employeeService)
        {
            this._employeeService = employeeService;
            this._returnModel = new ReturnModel();
            _returnModel.Message = Constants.SERVER_ERROR_OCCURRED;
        }
        public async Task<ActionResult> Index()
       {         
                return View("~/Areas/User/Views/Login/Index.cshtml");        
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> LoggedIn(LoginViewModel model)
        {
            if (!ModelState.IsValid)
            {
                _returnModel.Message = ModelState.FirstOrDefault(x => x.Value.Errors.Any()).Value.Errors.FirstOrDefault().ErrorMessage;
                return Json(_returnModel);
            }
            _returnModel = await _employeeService.Login(model);
            if(_returnModel.IsSuccess)
            {
                //return View("~/Areas/User/Employee/Index.cshtml");
                return Json(_returnModel);
            }
            return Json(_returnModel);
        }
    }
}

Employee/Employee.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Employee.Web.Models;

namespace Employee.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Employee/Employee.Web/Areas/User/Views/EmpForm/Index.cshtml
@model Employee.Web.EmployeeDetailsEntity 
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";

}
<style>
    .errBox {
        border-left: 3px solid red;
    }

    .error {
        color: red;
    }
</style>

<div class="content-wrapper container">

    <div id="divEmployeeContainer">
        @using (Html.BeginForm("PostEmpolyee", "Employee", FormMethod.Post, new { @area = "Admin", @id = "frmEmployee", @name = "frmEmployee" }))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(x => x.ID)

            <div class="container">
                <br /><br />

                <div class="row" style="margin-right: 10%" ;>
                    <div class="col-md-6 well form-horizontal">

                        <div class="form-group">
                            <div class="col-md-4">
                                <label class="control-label">EMPLOYEE ID</label>
                            </div>



                            <div class="col-md-8">
                                @Html.EditorFor(x => x.EMPLOYEE_ID, new { htmlAttributes = new { @autocomplete = "off", @class = "form-control requiredField", @placeholder = "EMPLOYEE_ID", @title = "EMPLOYEE_ID", @maxLength = 30 } })
                            </div>
                            <div class="col-md-4">
                                <label class="control-label">NAME</label>
                            </div>
                            <div class="col-md-8">
                                @Html.EditorFor(x => x.EMPLOYEE_NAME, new { htmlAttributes = new { @autocomplete = "off", @class = "form-control requiredField", @placeholder = "EMPLOYEE_NAME", @title = "EMPLOYEE_NAME", @maxLength = 30 } })
                            </div>
                            <div class="col-md-4">
                                <label class="control-label">DESIGNATION</label>
                            </div>
                            <div class="col-md-8">
                                @Html.EditorFor(x => x.EMPLOYEE_DESIGNATION, new { htmlAttributes = new { @autocomplete = "off", @class = "form-control requiredField", @placeholder = "EMPLOYEE_DESIGNATION", @title = "EMPLOYEE_DESIGNATION", @maxLength = 30 } })
                            </div>
                            <div class="col-md-4">
                                <label class="control-label">SALARY</label>
                            </div>
                            <div class="col-md-8">
                                @Html.EditorFor(x => x.EMPLOYEE_SALARY, new { htmlAttributes = new { @autocomplete = "off", @type = "number" ,@class = "form-control requiredField", @placeholder = "EMPLOYEE_SALARY", @title = "EMPLOYEE_SALARY", @maxLength = 30 } })
                            </div>
                            <div class="col-md-4">
                                <label class="control-label">DEPARTMENT</label>
                            </div>
                            <div class="col-md-8">
                                @Html.EditorFor(x => x.EMPLOYEE_DEPARTMENT, new { htmlAttributes = new { @autocomplete = "off", @class = "form-control requiredField", @placeholder = "EMPLOYEE_DEPARTMENT", @title = "EMPLOYEE_DEPARTMENT", @maxLength = 30 } })
                            </div>
                            <div class="col-md-4">
                                <label class="control-label">LOCATION</label>
                            </div>
                            <div class="col-md-8">
                                @Html.EditorFor(x => x.EMPLOYEE_LOCATION, new { htmlAttributes = new { @autocomplete = "off", @class = "form-control requiredField", @placeholder = "EMPLOYEE_LOCATION", @title = "EMPLOYEE_LOCATION", @maxLength = 30 } })
                            </div>
                            <div class="col-md-4">
                                <label class="control-label">DOB</label>
                            </div>
                            <div class="col-md-8">
                                @Html.EditorFor(x => x.EMPLOYEE_DOB, "{0:dd-MM-yyyy}",new { htmlAttributes = new { @autocomplete = "off", @class = "form-control requiredField", @placeholder = "EMPLOYEE_DOB", @title = "EMPLOYEE_DOB", @maxLength = 30 } })
                            </div>
                        </div>

                        <div style="margin:5%" class="form-group pull-right">
                            <a href="@Url.Action("Index","Employee")" class="btn btn-default">Cancel</a>
                            <button type="button" class="btn btn-primary pull-right" onclick="javascript:InsertUpdateEmployee();">Submit</button>

                        </div>
                    </div>
                </div>


                <table id="tblEmployee" class="table table-bordered table-striped">
                    <thead>
                        <tr style="background-color:#367fa9;color:white">
                            <th style="width:400px">Emp_Id</th>
                            <th style="width:400px">Emp_Name</th>
                            <th style="width:400px">Emp_Desig</th>
                            <th style="width:400px">Emp_Salary</th>
                            <th style="width:400px">Emp_Dept.</th>
                            <th style="width:400px">Emp_Loc.</th>
                            <th style="width:400px">Emp_DOB</th>
                            <th style="width:200px">Action</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in ViewBag.EmployeeList)
                        {
                            <tr style="background-color:white">
                                <td>@item.EMPLOYEE_ID</td>
                                <td>@item.EMPLOYEE_NAME</td>
                                <td>@item.EMPLOYEE_DESIGNATION</td>
                                <td>@item.EMPLOYEE_SALARY</td>
                                <td>@item.EMPLOYEE_DEPARTMENT</td>
                                <td>@item.EMPLOYEE_LOCATION</td>
                                <td>@item.EMPLOYEE_DOB</td>
                                <td>
                                    <a href="@Url.Action("EditEmployee","Employee",new { @area = "User", @EmployeeID = item.ID })">Edit </a>
                                    @if (item.StatusId == 2)
                                    {
                                        <a href="javascript:void(0)" onclick="ActivateEmployee(@item.ID)"> | Activate </a>
                                    }
                                    else
                                    {
                                        <a href="javascript:void(0)" onclick="DeactivateEmployee(@item.ID)">| Deactivate </a>
                                    }
                                    <a href="javascript:void(0)" onclick="DeleteEmployee(@item.ID)">| Delete </a>
                                </td>

                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }
    </div>
</div>

@section scripts{
    <script src="~/Assests/custom-scripts/Employee.js"></script>
}

Employee/Employee.Web/Areas/User/Views/Login/Index.cshtml
@model Employee.Web.UserEntity

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";

}
<style>
    .errBox {
        border-left: 3px solid red;
    }

    .error {
        color: red;
    }
</style>

<div class="content-wrapper container">

    <div id="divLoginContainer">
        @using (Html.BeginForm("PostLogin", "Login", FormMethod.Post, new { @area = "Admin", @id = "frmLogin", @name = "frmLogin" }))
        {
            @Html.AntiForgeryToken()
            @*@Html.HiddenFor(x => x.Id)*@

            <div class="container">
                <br /><br />

                <div class="row" style="margin-right: 10%" ;>
                    <div class="col-md-6 well form-horizontal">

                        <div class="form-group">
                            <div class="col-md-4">
                                <label class="control-label">USERNAME</label>
                            </div>



                            <div class="col-md-8">
                                @Html.EditorFor(x => x.USERNAME, new { htmlAttributes = new { @autocomplete = "off", @class = "form-control requiredField", @placeholder = "Username", @title = "Username", @maxLength = 30 } })
                            </div>
                            <div class="col-md-4">
                                <label class="control-label">USERPASSWORD</label>
                            </div>
                            <div class="col-md-8">
                                @Html.EditorFor(x => x.USERPASSWORD, new { htmlAttributes = new { @autocomplete = "off", @class = "form-control requiredField", @placeholder = "Password", @title = "Password", @maxLength = 30 } })
                            </div>
                        </div>

                        <div style="margin:5%" class="form-group pull-right">
                            <a href="@Url.Action("Index","Login")" class="btn btn-default">Cancel</a>
                            <button type="button" class="btn btn-primary pull-right" onclick="javascript:InsertUpdateLogin();">Submit</button>

                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

@section scripts{
    <script src="~/Assests/custom-scripts/Login.js"></script>
}

Employee/Employee.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Employee/Employee.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Employee.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Employee.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Employee.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Employee/Employee.Web/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Ecommerce</title>
    <link href="~/Assests/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    <link rel="stylesheet" href="~/Assests/bower_components/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Assests/bower_components/Ionicons/css/ionicons.min.css">
    <link rel="stylesheet" href="~/Assests/dist/css/AdminLTE.min.css">
    <link rel="stylesheet" href="~/Assests/dist/css/skins/_all-skins.min.css">
    <link rel="stylesheet" href="~/Assests/bower_components/jvectormap/jquery-jvectormap.css">
    <link rel="shortcut icon" href="~/Assests/images/cart.png" type="image/x-icon" />

</head>
<body class="hold-transition skin-blue sidebar-mini">

    <div class="wrapper">
        @*<header class="main-header">
            <a href="#" class="logo">
                <span class="logo-mini"><b>JP</b></span>
                <span class="logo-lg"><b>Job Portal</b> </span>
            </a>

            <nav class="navbar navbar-static-top">
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">

                        <li class="dropdown user user-menu">
                            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-user-circle"></i>
                                <span class="hidden-xs">Admin</span>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="user-header">
                                    <i class="fa fa-user-circle fa-3x" style="color:white"></i>
                                    <p>
                                        Admin
                                    </p>
                                </li>

                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="#" class="btn btn-default btn-flat">Profile</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="#" class="btn btn-default btn-flat">Log out</a>
                                    </div>
                                </li>
                            </ul>
                        </li>

                    </ul>
                </div>
            </nav>
        </header>

        <aside class="main-sidebar">
            <section class="sidebar">
                <div class="user-panel">
                    <div class="pull-left image">
                        <i style="color:white" class="fa fa-user-circle fa-3x"></i>
                    </div>
                    <div class="pull-left info">
                        <p> Admin</p>
                        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                    </div>
                </div>

                <ul class="sidebar-menu" data-widget="tree">
                    <li class=" treeview">
                        <a href="#">
                            <i class="fa fa-dashboard"></i> <span> Masters</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                           
                        </ul>
                    </li>
                </ul>

            </section>
        </aside>*@
        @RenderBody()
    </div>

    <script src="~/Assests/lib/jquery/dist/jquery.js"></script>
    <script src="~/Assests/bower_components/jquery-ui/jquery-ui.min.js"></script>
    <script>
        $.widget.bridge('uibutton', $.ui.button);
    </script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    <script src="~/Assests/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/Assests/bower_components/raphael/raphael.min.js"></script>
    <script src="~/Assests/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
    <script src="~/Assests/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="~/Assests/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
    <script src="~/Assests/bower_components/moment/min/moment.min.js"></script>
    <script src="~/Assests/bower_components/fastclick/lib/fastclick.js"></script>
    <script src="~/Assests/dist/js/adminlte.min.js"></script>
    <script src="~/Assests/dist/js/demo.js"></script>
    <script src="~/Assests/validation/custom-validation.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    @RenderSection("scripts", required: false)
</body>

</html>